// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/api/v2/index.en-US":{"path":"en-US/api/v2","id":"docs/api/v2/index.en-US","parentId":"DocLayout"},"docs/api/v2/index.ko-KR":{"path":"ko-KR/api/v2","id":"docs/api/v2/index.ko-KR","parentId":"DocLayout"},"docs/api/v3/index.en-US":{"path":"en-US/api/v3","id":"docs/api/v3/index.en-US","parentId":"DocLayout"},"docs/api/v3/index.ko-KR":{"path":"ko-KR/api/v3","id":"docs/api/v3/index.ko-KR","parentId":"DocLayout"},"docs/CHANGELOG.en-US":{"path":"en-US/Changelog","id":"docs/CHANGELOG.en-US","parentId":"DocLayout"},"docs/CHANGELOG.ko-KR":{"path":"ko-KR/Changelog","id":"docs/CHANGELOG.ko-KR","parentId":"DocLayout"},"docs/EXAMPLE.en-US":{"path":"en-US/Example","id":"docs/EXAMPLE.en-US","parentId":"DocLayout"},"docs/EXAMPLE.ko-KR":{"path":"ko-KR/Example","id":"docs/EXAMPLE.ko-KR","parentId":"DocLayout"},"docs/api/v2/index":{"path":"api/v2","id":"docs/api/v2/index","parentId":"DocLayout"},"docs/api/v3/index":{"path":"api/v3","id":"docs/api/v3/index","parentId":"DocLayout"},"docs/index.en-US":{"path":"en-US/","id":"docs/index.en-US","parentId":"DocLayout"},"docs/index.ko-KR":{"path":"ko-KR/","id":"docs/index.ko-KR","parentId":"DocLayout"},"docs/CHANGELOG":{"path":"Changelog","id":"docs/CHANGELOG","parentId":"DocLayout"},"docs/EXAMPLE":{"path":"Example","id":"docs/EXAMPLE","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.27.1_@swc+helpers@0.5.1_@types+node@22.15.17_eslint@8.57.1_jest@27._k52o7bsjhc7apl3at7eg3h22hq/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.27.1_@swc+helpers@0.5.1_@types+node@22.15.17_eslint@8.57.1_jest@27._k52o7bsjhc7apl3at7eg3h22hq/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/api/v2/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__api__v2__index.en-US.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.en-US.md')),
'docs/api/v2/index.ko-KR': React.lazy(() => import(/* webpackChunkName: "docs__api__v2__index.ko-KR.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.ko-KR.md')),
'docs/api/v3/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__api__v3__index.en-US.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.en-US.md')),
'docs/api/v3/index.ko-KR': React.lazy(() => import(/* webpackChunkName: "docs__api__v3__index.ko-KR.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.ko-KR.md')),
'docs/CHANGELOG.en-US': React.lazy(() => import(/* webpackChunkName: "docs__CHANGELOG.en-US.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.en-US.md')),
'docs/CHANGELOG.ko-KR': React.lazy(() => import(/* webpackChunkName: "docs__CHANGELOG.ko-KR.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.ko-KR.md')),
'docs/EXAMPLE.en-US': React.lazy(() => import(/* webpackChunkName: "docs__EXAMPLE.en-US.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.en-US.md')),
'docs/EXAMPLE.ko-KR': React.lazy(() => import(/* webpackChunkName: "docs__EXAMPLE.ko-KR.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.ko-KR.md')),
'docs/api/v2/index': React.lazy(() => import(/* webpackChunkName: "docs__api__v2__index.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.md')),
'docs/api/v3/index': React.lazy(() => import(/* webpackChunkName: "docs__api__v3__index.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.md')),
'docs/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__index.en-US.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.en-US.md')),
'docs/index.ko-KR': React.lazy(() => import(/* webpackChunkName: "docs__index.ko-KR.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.ko-KR.md')),
'docs/CHANGELOG': React.lazy(() => import(/* webpackChunkName: "docs__CHANGELOG.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.md')),
'docs/EXAMPLE': React.lazy(() => import(/* webpackChunkName: "docs__EXAMPLE.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.27.1_@swc+helpers@0.5.1_@types+node@22.15.17_eslint@8.57.1_jest@27._k52o7bsjhc7apl3at7eg3h22hq/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
