// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.27.1_@swc+helpers@0.5.1_@types+node@22.15.17_eslint@8.57.1_jest@27._k52o7bsjhc7apl3at7eg3h22hq/node_modules/dumi/theme-default/slots/NotFound/index.js';
