// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.en-US.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.en-US.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.ko-KR.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.ko-KR.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.en-US.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.en-US.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.ko-KR.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.ko-KR.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.en-US.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.en-US.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.ko-KR.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.ko-KR.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.en-US.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.en-US.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.ko-KR.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.ko-KR.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.en-US.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.en-US.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.ko-KR.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.ko-KR.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.md?type=demo-index';

export const filesMeta = {
  'docs/api/v2/index.en-US': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.en-US.md?type=text'),
  },
  'docs/api/v2/index.ko-KR': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs__ko-KR" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.ko-KR.md?type=text'),
  },
  'docs/api/v3/index.en-US': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.en-US.md?type=text'),
  },
  'docs/api/v3/index.ko-KR': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs__ko-KR" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.ko-KR.md?type=text'),
  },
  'docs/CHANGELOG.en-US': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.en-US.md?type=text'),
  },
  'docs/CHANGELOG.ko-KR': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs__ko-KR" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.ko-KR.md?type=text'),
  },
  'docs/EXAMPLE.en-US': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.en-US.md?type=text'),
  },
  'docs/EXAMPLE.ko-KR': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs__ko-KR" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.ko-KR.md?type=text'),
  },
  'docs/api/v2/index': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v2/index.md?type=text'),
  },
  'docs/api/v3/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/api/v3/index.md?type=text'),
  },
  'docs/index.en-US': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.en-US.md?type=text'),
  },
  'docs/index.ko-KR': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs__ko-KR" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.ko-KR.md?type=text'),
  },
  'docs/CHANGELOG': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/CHANGELOG.md?type=text'),
  },
  'docs/EXAMPLE': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/EXAMPLE.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/hotoo/workbench/github.com/hotoo/pinyin/docs/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
